### ISSUE TITLE
3.6.0 breaks interface exports

### ISSUE THREAD

**Issue by buu700** [jsdoc/jsdoc#1644] opened 2019-05-05 14:52 UTC
3.6.0 seems to have regressed in handling `@interface` and/or `@export`.

Using protobufjs with jsdoc@3.5.5 works as expected. After updating to 3.6.0, the `pbts` command that takes a generated JS file as input and outputs a TypeScript type definition file fails to export required interfaces.

I don't know exactly what protobufjs is doing under-the-hood, but it looks like [this](https://github.com/protobufjs/protobuf.js/blob/8a85863/cli/pbts.js#L99) is the relevant function that uses jsdoc.

### Input code

Protobuf code like this:

```proto
/** A class. */
message Balls {
	/** A string. */
	required string test = 1;
}
```

Would output code that includes this:

```js
/**
 * Properties of a Balls.
 * @exports IBalls
 * @interface IBalls
 * @property {string} test A string.
 */
```

### Expected behavior

The final output should include an interface `IBalls` (and a class `Balls` that implements `IBalls`).

### Current behavior

No `IBalls`.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.6.0
| Node.js          | 10.15.3
| npm              | 6.4.1
| Operating system | Debian 9.9

**Comment by hegemonic** [comment] 2019-05-05 19:38
When I save your sample output as a JS file and run JSDoc 3.6.1 on that file, it generates the appropriate docs:

<img width="975" alt="Screen Shot 2019-05-05 at 12 34 24 PM" src="https://user-images.githubusercontent.com/1522391/57199321-71cfc300-6f32-11e9-82b0-d61117ff6d64.png">

I'm guessing that your real input file is more complicated. Can you point me to the repo that contains the full input file, or share it with me in a gist (privately if necessary)?

**Comment by bcoe** [comment] 2019-05-06 19:55
We are bumping into similar issues in the library:

https://github.com/googleapis/nodejs-resource

When generating jsdoc with `3.5.5`, a page is generated correctly for the:

`export {Project};`

and

`export {Resource};`

On `3.6.x` no `Resource.html` or `Project.html` is generated.

**Comment by hegemonic** [comment] 2019-05-07 03:24
Thanks for the pointer, @bcoe. I can reproduce the issue with that repo, and this is definitely a bug in JSDoc 3.6.x. I'm continuing to investigate.

The temporary solution is to pin to JSDoc 3.5.5.

**Comment by hegemonic** [comment] 2019-05-07 03:47
Looks like the culprit is cc66657512cb2ac78d80fffa1ac9a4c1f1bfdce3. I'll have to think about how to fix this regression without regressing #1129 as well.

Fix coming soon, but "soon" might mean "a few days from now."

**Comment by bcoe** [comment] 2019-05-07 04:24
@hegemonic thank you for digging into this 👍

**Comment by hegemonic** [comment] 2019-05-12 16:49
Fixed on master and JSDoc 3.6.2, which I just released. Thanks for your patience!

**Closed by hegemonic** 2019-05-12 16:49 UTC
Labels: bugfix

**Comment by bcoe** [comment] 2019-05-13 03:57
@hegemonic thank you 👍, I will start testing it out on some repos tomorrow.

**Comment by buu700** [comment] 2019-11-20 16:24
Hey @hegemonic, I just tested this with both 3.6.2 and 3.6.3 on Node versions 10.17.0 and 12.13.1, and I'm still running into the original issue.

3.5.5 continues to work as expected, aside from #1643 (which I have a [temporary workaround](https://github.com/protobufjs/protobuf.js/issues/1306#issuecomment-549204730) for, so not a blocker atm).

**Comment by brettz9** [comment] 2019-12-05 04:48
Could this be reopened?

**Comment by SharpDevSa** [comment] 2020-03-06 10:36
pbts with JSDoc  3.6.3 does not output the correct result for Enums as well. 
Enum is missing.
Node version: 12.16.0
protobufjs: 6.8.8 
JSDoc was directly updated in protobufjs package,

**Comment by buu700** [comment] 2021-05-13 17:04
I can confirm that this is still an issue with jsdoc 3.6.6 and protobufjs 6.11.2. Please reopen, @hegemonic.
