### ISSUE TITLE
3.6.1: documented inner classes missing from output

### ISSUE THREAD

**Issue by 75lb** [jsdoc/jsdoc#1650] opened 2019-05-09 14:53 UTC
I'm using jsdoc v3.6.1, node v12.1 on macOS. This issue breaks [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown). 

I have this input code: 

```js
/**
 * @module farm
 */

/**
 * the farm
 * @alias module:farm
 */
class Farm {
 /**
  * the constructor
  */
  constructor () {}
}

module.exports = Farm
```

Here is the explain output using jsdoc 3.5.5: 

```json
[
    {
        "comment": "/**\n * @module farm\n */",
        "meta": {
            "filename": "issue.js",
            "lineno": 1,
            "columnno": 0,
            "path": "/Users/lloyd/Documents/tmp",
            "code": {}
        },
        "kind": "module",
        "name": "farm",
        "longname": "module:farm"
    },
    {
        "comment": "/**\n * the farm\n * @alias module:farm\n */",
        "meta": {
            "range": [
                67,
                131
            ],
            "filename": "issue.js",
            "lineno": 9,
            "columnno": 0,
            "path": "/Users/lloyd/Documents/tmp",
            "code": {
                "id": "astnode100000002",
                "name": "Farm",
                "type": "ClassDeclaration",
                "paramnames": []
            }
        },
        "classdesc": "the farm",
        "alias": "module:farm",
        "name": "module:farm",
        "longname": "module:farm",
        "kind": "class",
        "description": "the constructor",
        "params": []
    },
    {
        "comment": "/**\n  * the constructor\n  */",
        "meta": {
            "range": [
                112,
                129
            ],
            "filename": "issue.js",
            "lineno": 13,
            "columnno": 2,
            "path": "/Users/lloyd/Documents/tmp",
            "code": {
                "id": "astnode100000005",
                "name": "Farm",
                "type": "MethodDefinition",
                "paramnames": []
            },
            "vars": {
                "": null
            }
        },
        "description": "the constructor",
        "name": "module:farm",
        "longname": "module:farm",
        "kind": "class",
        "alias": "module:farm",
        "params": [],
        "undocumented": true
    },
    {
        "comment": "",
        "meta": {
            "range": [
                133,
                154
            ],
            "filename": "issue.js",
            "lineno": 16,
            "columnno": 0,
            "path": "/Users/lloyd/Documents/tmp",
            "code": {
                "id": "astnode100000010",
                "name": "module.exports",
                "type": "Identifier",
                "value": "Farm",
                "paramnames": []
            }
        },
        "undocumented": true,
        "name": "module:farm",
        "longname": "module:farm",
        "kind": "member"
    },
    {
        "kind": "package",
        "longname": "package:undefined",
        "files": [
            "/Users/lloyd/Documents/tmp/issue.js"
        ]
    }
]
```

Here is the explain output using v3.6.1 - **notice `"undocumented": true` has been set on both the class and constructor doclets despite the fact they are both documented.**

Since jsdoc2md excludes `undocumented: true` doclets from its output, the jsdoc2md output is now broken because many documented class and constructors are missing.

```json
[
  {
    "comment": "/**\n * @module farm\n */",
    "meta": {
      "filename": "issue.js",
      "lineno": 1,
      "columnno": 0,
      "path": "/Users/lloyd/Documents/tmp",
      "code": {}
    },
    "kind": "module",
    "name": "farm",
    "longname": "module:farm"
  },
  {
    "comment": "/**\n * the farm\n * @alias module:farm\n */",
    "meta": {
      "range": [
        67,
        131
      ],
      "filename": "issue.js",
      "lineno": 9,
      "columnno": 0,
      "path": "/Users/lloyd/Documents/tmp",
      "code": {
        "id": "astnode100000002",
        "name": "Farm",
        "type": "ClassDeclaration",
        "paramnames": []
      }
    },
    "classdesc": "the farm",
    "alias": "module:farm",
    "name": "module:farm",
    "longname": "module:farm",
    "kind": "class",
    "undocumented": true
  },
  {
    "comment": "/**\n  * the constructor\n  */",
    "meta": {
      "range": [
        112,
        129
      ],
      "filename": "issue.js",
      "lineno": 13,
      "columnno": 2,
      "path": "/Users/lloyd/Documents/tmp",
      "code": {
        "id": "astnode100000005",
        "name": "Farm",
        "type": "MethodDefinition",
        "paramnames": []
      },
      "vars": {
        "": null
      }
    },
    "description": "the constructor",
    "name": "module:farm",
    "longname": "module:farm",
    "kind": "class",
    "alias": "module:farm",
    "params": [],
    "undocumented": true
  },
  {
    "comment": "/**\n  * the constructor\n  */",
    "meta": {
      "range": [
        112,
        129
      ],
      "filename": "issue.js",
      "lineno": 13,
      "columnno": 2,
      "path": "/Users/lloyd/Documents/tmp",
      "code": {
        "id": "astnode100000005",
        "name": "Farm",
        "type": "MethodDefinition",
        "paramnames": []
      }
    },
    "name": "module:farm",
    "longname": "module:farm",
    "kind": "class",
    "description": "the constructor",
    "alias": "module:farm",
    "classdesc": "the farm",
    "params": []
  },
  {
    "comment": "",
    "meta": {
      "range": [
        133,
        154
      ],
      "filename": "issue.js",
      "lineno": 16,
      "columnno": 0,
      "path": "/Users/lloyd/Documents/tmp",
      "code": {
        "id": "astnode100000010",
        "name": "module.exports",
        "type": "Identifier",
        "value": "Farm",
        "paramnames": []
      }
    },
    "undocumented": true,
    "name": "module:farm",
    "longname": "module:farm",
    "kind": "member"
  },
  {
    "kind": "package",
    "longname": "package:undefined",
    "files": [
      "/Users/lloyd/Documents/tmp/issue.js"
    ]
  }
]
```

**Comment by 75lb** [comment] 2019-05-12 11:14
Here is another example which demonstrates how documented, inner classes are not rendered in jsdoc 3.6.1 output. Input source code:

```js
/**
 * Exports a farm. Documents inner classes.
 * @module farm
 */

/**
 * The farm
 * @alias module:farm
 */
class Farm {
 /**
  * the constructor
  */
  constructor () {
    /**
     * farm equipment
     * @type module:farm~Equipment
     */
    this.equipment = new Equipment()
  }
}

/**
* Equipment class
*/
class Equipment {
 constructor () {
   /**
    * the tractor
    * @type module:farm~Tractor
    */
   this.tractor = new Tractor()
 }
}

/**
* Tractor class
*/
class Tractor {
  constructor () {
    /**
     * engine details
     */
    this.engine = {
      /**
       * who built
       */
      manufacturer: 'one',
      /**
       * the size
       */
      size: 2
    }
  }

  /**
   * a static property on Tractor
   */
  static something () {}
}

module.exports = Farm
```

The above code rendered in jsdoc 3.6, notice the inner classes (`Equipment` and `Tractor`) are not shown: 

![3 6](https://user-images.githubusercontent.com/1247980/57581365-5aeb1c80-74ae-11e9-8cb5-2eda0f328d3e.png)

The above code rendered in jsdoc 3.5.5. Notice the inner classes are shown correctly. 

![3 5 menu](https://user-images.githubusercontent.com/1247980/57581367-63435780-74ae-11e9-82c6-813923a8322b.png)

![3 5 class](https://user-images.githubusercontent.com/1247980/57581355-2e370500-74ae-11e9-9628-6edf73676ecb.png)

Here is the v3.5.5 and v3.6.1 JSON output and the diff between them: 
https://gist.github.com/75lb/3f7a0594fdc987cfe588f4e9db138b1f

**Comment by hegemonic** [comment] 2019-05-12 16:27
Duplicate of #1644. Fix coming very soon.

**Closed by hegemonic** 2019-05-12 16:27 UTC

**Comment by sa-spag** [comment] 2019-05-24 15:24
Hey @hegemonic, thanks for the recent efforts on JSDoc. Unfortunately it seems like this is not fixed to me. I've came up with an even simpler example:
```js
// Interface.js

/**
 * @interface
 */
class Interface {
  constructor() {}
}
```

Run `npx jsdoc Interface.js -X` and here is the diff between 3.5.5 and 3.6.2:

```diff
diff --git a/3.5.5.json b/3.6.2.json
index fe59b96..550cbae 100644
--- a/3.5.5.json
+++ b/3.6.2.json
@@ -21,7 +21,7 @@
         "name": "Interface",
         "longname": "Interface",
         "scope": "global",
-        "params": []
+        "undocumented": true
     },
     {
         "comment": "",
@@ -51,6 +51,29 @@
         "scope": "global",
         "params": []
     },
+    {
+        "comment": "",
+        "meta": {
+            "range": [
+                42,
+                58
+            ],
+            "filename": "Interface.js",
+            "lineno": 5,
+            "columnno": 2,
+            "path": "/Users/alexis/Documents/misc",
+            "code": {
+                "id": "astnode100000005",
+                "name": "Interface",
+                "type": "MethodDefinition",
+                "paramnames": []
+            }
+        },
+        "name": "Interface",
+        "longname": "Interface",
+        "kind": "class",
+        "scope": "global"
+    },
     {
         "kind": "package",
         "longname": "package:undefined",
```
