### ISSUE TITLE
JSDoc parser API for source code (text)

### ISSUE THREAD

**Issue by HamedFathi** [jsdoc/jsdoc#1610] opened 2019-02-04 10:46 UTC
Is it possible to access API instead of CLI? I want to work with source code (text) directly and get the result in code.

Can anyone guide me? I need API like [Doctrine](https://github.com/eslint/doctrine).

**Comment by JustinBeaudry** [comment] 2019-03-12 04:17
I've been referencing https://github.com/jsdoc3/jsdoc/blob/master/jsdoc.js and https://github.com/jsdoc3/jsdoc/blob/master/cli.js on how to do this. It doesn't look like they have a public API; however, you could do it yourself by referencing the above. I'm just trying this myself now so if I find anything out I'll post back here.

**Comment by HamedFathi** [comment] 2019-03-12 05:59
@JustinBeaudry Thanks :D

**Comment by JustinBeaudry** [comment] 2019-03-13 00:54
@HamedFathi I managed to get it to work, but after reflecting I decided that it would be fragile, and is probably not a good idea. In the end, I opted for using `child_process` instead:

```javascript
const jsdoc = () => {
  return new Promise((resolve, reject) => {
    // using locally installed jsdoc
    const jsdoc = spawn('npx', [
      'jsdoc',
      // pass jsdoc cli options here
      '-c',
      'conf.json',
      '-X'
    ]);
    let output = '';
    let err = '';
    jsdoc.stdout.on('data', data => { output += data });
    jsdoc.stderr.on('data', data => { err += data });
    jsdoc.on('close', code => { code > 0 ? reject(err) : resolve(output) });
  });
};
```

In this case, I wanted to write a test for my plugin so I use `--explain (-X)` to just have jsdoc return JSON output. Then in another function, I JSON parse the output. Not sure if that's helpful, but I honestly think this option is better than using the undocumented API's.

**Comment by hegemonic** [comment] 2019-05-05 20:16
Duplicate of #938.

**Closed by hegemonic** 2019-05-05 20:16 UTC
