### ISSUE TITLE
Link to internal type within module

### ISSUE THREAD

**Issue by koryukov** [jsdoc/jsdoc#1533] opened 2018-06-06 07:00 UTC
I am tryng to document my JavaScript library using JSDoc. If I use `@module` tag I have to use fully qualified type name.

### Current behavior

For example I have to do the following to link to the `MyType` type:

```js
/** @module my/module */

/** My function definition
 * @public
 * @method
 * @param {module:my/module~MyType} options Method options
 */
function myFunction(options) {
}

/** My type definition
 * @typedef {object} MyType
 * @property {string} prop1 Property 1
 * @property {number} prop2 Property 2
 */
```

It solves issue #969, but seems cumbersome. Moreover the IntelliSense doesn't create tooltips for such arguments.

### Expected behavior

Is there way to detect types from internal scope of a module using short names? For example:

```js
/** @module my/module */

/** My function definition
 * @public
 * @method
 * @param {MyType} options Method options
 */
function myFunction(options) {
}

/** My type definition
 * @typedef {object} MyType
 * @property {string} prop1 Property 1
 * @property {number} prop2 Property 2
 */
```

### Environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  3.5.5
| Node.js          |  8.11.1
| npm              |  5.6.0
| Operating system | Windows 7 Professional (x64)
| Visual Studio Community 2017 | 15.7.3

**Comment by meshu** [comment] 2018-08-14 18:13
To add to this, the closure compiler does not understand the module: prefix so you effectively cant use jsdoc with a module codebase along with the closure compiler, which is sad.

**Comment by hegemonic** [comment] 2019-05-05 21:47
Duplicate of #1645, which is a catch-all for module-related issues.

**Closed by hegemonic** 2019-05-05 21:47 UTC
