### ISSUE TITLE
Support `import` syntax (and possibly deprecate `module` syntax)

### ISSUE THREAD

**Issue by brettz9** [jsdoc/jsdoc#1632] opened 2019-04-07 03:38 UTC
### Expected behavior

Allow this Typescript syntax:

```js
/**
 * @param p { import("./a").Pet }
*/
```

I'd personally also hope to see `module:` deprecated (at least eventually):

```js
/**
 * @param p { module:a.Pet }
*/
```

...because:

1. According to [this comment](https://github.com/jsdoctypeparser/jsdoctypeparser/issues/50#issuecomment-480340239), it is the only deliberate deviation of TypeScript from jsdoc and the only expected one.
2. It is useful in its own right for documentation to make clear from where a module is being obtained, whether the path is a relative one, or as is apparently also allowed, one based on the well-used Node resolution algorithm.

### Current behavior

Currently, the `module` syntax is not compatible with those wishing to move to Typescript (or considering doing so), or those using Typescript who wish to confine themselves to the subset supported by jsdoc3 so as to be able to take advantage of jsdoc3/jsdoc.

**Comment by GrosSacASac** [comment] 2019-04-08 14:25
jsdoc does not follow imports by default https://github.com/jsdoc3/jsdoc/issues/1577

**Comment by brettz9** [comment] 2019-04-08 14:50
I am referring to Typescript's style of imports; see, e.g.: https://github.com/openlayers/jsdoc-plugin-typescript#typescript

**Comment by brettz9** [comment] 2019-04-10 00:11
The quotation marks in `@external` targeted paths appears to be another one of the few "won't fix"'s of TypeScript relative to JSDoc (see https://github.com/jsdoctypeparser/jsdoctypeparser/issues/58#issuecomment-481331955 ), so I should make explicit here the desire that the desired `import` statements also handle the case of `@external` paths, i.e., non-resolved paths.

Hopefully if accepting this issue as I hope would be the case for mutual compatibility, JSDoc, might allow, at least through plugin, the ability to check such non-browser-resolvable paths (especially according to the Node Resolution Algorithm), so that they could be confirmed in some way. 

So that, e.g.:
```js
/** @type {import("jQuery.fn").starfairy} */
```

...could be confirmed as a valid path, and even possibly link to source code.

Actually, since jQuery doesn't export "fn", I guess it should be:

```js
/** @type {import("jQuery").fn.starfairy} */
```

@sandersn

**Comment by hegemonic** [comment] 2019-05-09 05:07
I think this qualifies as a duplicate of #1645.

**Closed by hegemonic** 2019-05-09 05:07 UTC

**Comment by nbilyk** [comment] 2021-01-27 13:45
A jsdoc plugin to workaround to this problem:
[https://github.com/polyforest/jsdoc-tsimport-plugin/](https://github.com/polyforest/jsdoc-tsimport-plugin/)
